# Phase 08 — Fusion and Shortcut Analysis

## tl;dr

This executed diagnostic notebook initializes and audits Phase 08 only. It performs no training, prediction, OOF generation, or fusion execution.

## Context & Methods

All data, feature membership, folds, and upstream model interfaces are read-only frozen inputs. Feature groups come from explicit manifests, never column-name prefix inference.

### Key Assumptions

- Primary without-performance remains the only main evidence.
- With-performance and performance-only are auxiliary shortcut-risk conditions.
- Initialization begins at `PENDING_CONTRACT_FREEZE`; the final section freezes the contract without modeling.

In [1]:
from pathlib import Path
import json, os, platform, sys
PHASE08_ROOT = Path.cwd().resolve()
sys.path.insert(0, str(PHASE08_ROOT / 'scripts'))
environment = {
    'python_version': sys.version,
    'python_executable': sys.executable,
    'platform': platform.platform(),
    'working_directory': os.getcwd(),
}
environment

{'python_version': '3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]',
 'python_executable': 'D:\\Computer\\anaconda3\\python.exe',
 'platform': 'Windows-11-10.0.26200-SP0',
 'working_directory': 'E:\\hdc-vr-pilot\\experiments\\phase_08_fusion_and_shortcut_analysis'}

## Data

### 1. Run the read-only initialization audit

In [2]:
from initialize_phase08 import DATA_PATHS, run_initialization
if (PHASE08_ROOT / 'configs' / 'phase08_frozen_contract.json').exists():
    summary = json.loads((PHASE08_ROOT / 'audits' / 'phase08_initialization_summary.json').read_text(encoding='utf-8'))
else:
    summary = run_initialization()
summary

{'phase08_directory_initialized': True,
 'phase08_name': 'Fusion and Shortcut Analysis',
 'summaries': {'primary': {'rows': 419,
   'subjects': 35,
   'unique_run_keys': 419,
   'predictive_features': 1176,
   'manifest_features_unique': True,
   'manifest_features_present_in_csv': True,
   'csv_columns': 1185},
  'with_performance': {'rows': 419,
   'subjects': 35,
   'unique_run_keys': 419,
   'predictive_features': 1235,
   'manifest_features_unique': True,
   'manifest_features_present_in_csv': True,
   'csv_columns': 1244},
  'performance_only': {'rows': 419,
   'subjects': 35,
   'unique_run_keys': 419,
   'predictive_features': 59,
   'manifest_features_unique': True,
   'manifest_features_present_in_csv': True,
   'csv_columns': 68}},
 'checksum_pass': {'primary': True,
  'with_performance': True,
  'performance_only': True,
  'folds': True,
  'with_performance_manifest': True,
  'performance_only_manifest': True},
 'three_dataset_run_key_alignment': True,
 'three_dataset_targe

### 2. Verify datasets, checksums, sizes, targets, and folds

In [3]:
input_fold_audit = json.loads((PHASE08_ROOT / 'audits' / 'phase08_input_and_fold_audit.json').read_text(encoding='utf-8'))
{
    'status': input_fold_audit['status'],
    'dataset_exists': {name: path.exists() for name, path in DATA_PATHS.items() if name != 'folds'},
    'sha256': input_fold_audit['actual_hashes'],
    'checksum_pass': input_fold_audit['checksum_pass'],
    'dataset_summaries': input_fold_audit['dataset_summaries'],
    'target_class_values': input_fold_audit['target_class_values'],
    'target_score_values': input_fold_audit['target_score_values'],
    'outer_folds': input_fold_audit['outer_folds'],
    'fold_checks': input_fold_audit['fold_checks'],
}

{'status': 'PASS',
 'dataset_exists': {'primary': True,
  'with_performance': True,
  'performance_only': True},
 'sha256': {'primary': '0a2aef89c01b43c3a4e5afe40b96797784627665490982731b2541f96b45fc44',
  'with_performance': '72977a2119e30e37996fb9f0e3404988c4977fb7d2b33992f87bf54bfe5decba',
  'performance_only': 'd602282ae41153886d1306494515f2e41a5e7e89a2cec5c192d44b9ca87a07a4',
  'folds': 'e4dc943af21851bace49345f6336f9c88f82613ca3a26b3c433efe7dfb041f6f',
  'with_performance_manifest': '91cc99688b0b5dca74f6ebabfe1447548cab7f86a4919725f8eff80987a492b3',
  'performance_only_manifest': '80c216dd6ece3f553d9a297dbda62b0505f0fa646c1ba4352abe9af553cb8b81'},
 'checksum_pass': {'primary': True,
  'with_performance': True,
  'performance_only': True,
  'folds': True,
  'with_performance_manifest': True,
  'performance_only_manifest': True},
 'dataset_summaries': {'primary': {'rows': 419,
   'subjects': 35,
   'unique_run_keys': 419,
   'predictive_features': 1176,
   'manifest_features_unique

## Results

### 3. Verify cross-dataset alignment and feature-set relations

In [4]:
alignment = json.loads((PHASE08_ROOT / 'audits' / 'phase08_dataset_alignment_audit.json').read_text(encoding='utf-8'))
alignment

{'status': 'PASS',
 'checks': {'three_dataset_run_key_alignment': True,
  'three_dataset_subject_target_fold_alignment': True,
  'with_performance_feature_union': True,
  'primary_performance_disjoint': True,
  'performance_only_matches_frozen_group': True,
  'manifest_roles_valid': True},
 'feature_set_relations': {'with_performance_equals_primary_union_performance': True,
  'primary_plus_performance_count_equals_with_performance': True,
  'primary_performance_intersection_count': 0,
  'performance_only_equals_frozen_performance_group': True},
 'identity_fields_compared_by_run_key': ['subject_id',
  'target_class',
  'target_score',
  'outer_fold']}

### 4. Verify manifest-derived fusion feature counts and exclusions

In [5]:
fusion = json.loads((PHASE08_ROOT / 'audits' / 'phase08_fusion_mapping_audit.json').read_text(encoding='utf-8'))
fusion

{'status': 'PASS',
 'membership_rule': 'EXPLICIT_FROZEN_MANIFEST_LISTS_ONLY_NO_PREFIX_INFERENCE',
 'combinations': {'physiological_plus_eye': {'feature_count': 649,
   'checks': {'feature_count_correct': True,
    'no_duplicate_columns': True,
    'membership_from_frozen_primary_manifest': True,
    'no_performance_features': True,
    'no_target_or_identifier_fields': True,
    'no_control_input_features': True,
    'no_unverified_features': True},
   'pass': True},
  'physiological_plus_eye_plus_head': {'feature_count': 808,
   'checks': {'feature_count_correct': True,
    'no_duplicate_columns': True,
    'membership_from_frozen_primary_manifest': True,
    'no_performance_features': True,
    'no_target_or_identifier_fields': True,
    'no_control_input_features': True,
    'no_unverified_features': True},
   'pass': True},
  'physiological_plus_eye_plus_head_plus_flight': {'feature_count': 1134,
   'checks': {'feature_count_correct': True,
    'no_duplicate_columns': True,
    'me

### 5. Persist the 59-feature performance shortcut-risk inventory

In [6]:
performance_risk = json.loads((PHASE08_ROOT / 'audits' / 'phase08_performance_feature_risk_inventory.json').read_text(encoding='utf-8'))
{
    'status': performance_risk['status'],
    'feature_count': performance_risk['feature_count'],
    'summary': performance_risk['summary'],
    'all_feature_names': [item['feature'] for item in performance_risk['features']],
    'target_identifier_exclusion_check': all(not item['reserved_field_name_collision'] for item in performance_risk['features']),
}

{'status': 'STATIC_AUDIT_COMPLETE',
 'feature_count': 59,
 'summary': {'reserved_name_collisions': 0,
  'label_adjacent_names': 0,
  'direct_target_copies': 0,
  'deterministic_target_transforms': 0},
 'all_feature_names': ['performance_cumulative_cumulative_airspeed_error_kts',
  'performance_cumulative_cumulative_glideslope_error_deg',
  'performance_cumulative_cumulative_localizer_error_deg',
  'performance_cumulative_cumulative_total_error',
  'performance_perfmetric_airspeed_error_kts_iqr',
  'performance_perfmetric_airspeed_error_kts_kurtosis',
  'performance_perfmetric_airspeed_error_kts_max',
  'performance_perfmetric_airspeed_error_kts_mean',
  'performance_perfmetric_airspeed_error_kts_median',
  'performance_perfmetric_airspeed_error_kts_min',
  'performance_perfmetric_airspeed_error_kts_missing_ratio',
  'performance_perfmetric_airspeed_error_kts_num_missing',
  'performance_perfmetric_airspeed_error_kts_range',
  'performance_perfmetric_airspeed_error_kts_rms',
  'performa

### 6. Verify Phase 04A, 04B, 06, and 07 frozen interfaces

In [7]:
upstream = json.loads((PHASE08_ROOT / 'audits' / 'phase08_upstream_freeze_interface_audit.json').read_text(encoding='utf-8'))
upstream

{'status': 'PASS',
 'interface_pass': {'phase04a': True,
  'phase04b': True,
  'phase06': True,
  'phase07': True},
 'interfaces': {'phase04a': {'sha256': '34ea8100d9406f9701750a441aa6537323c28bcdb194cb3fd3645c4f7de4a2e1',
   'checksum_pass': True,
   'frozen': True,
   'best_classifier': 'Gradient Boosting',
   'best_classifier_matches': True},
  'phase04b': {'sha256': 'e2c88b1139a50aab6d47b6477c7bceff74f8443095f9d039ea9af84b715ee790',
   'checksum_pass': True,
   'status': 'FROZEN',
   'best_regressor': 'Gradient Boosting Regressor',
   'best_regressor_matches': True},
  'phase06': {'sha256': 'cd94acdf0bcb463b5f48a7c84110a23059899b6b5bf156131694827d7d7bde66',
   'checksum_pass': True,
   'status': 'FROZEN',
   'classification_hdc': 'HDC+OnlineHD Hybrid',
   'classification_dimension': 5000,
   'regression_head': 'COMMON_ENCODER_READOUT_BASELINE',
   'regression_dimension': 10000},
  'phase07': {'sha256': '8569b48a8210f0ca1316d5a140d292edb892e2a556ea13ee299e9b97699af492',
   'checksum

### 7. Verify initialized artifacts and prohibited operations

In [8]:
artifact_audit = json.loads((PHASE08_ROOT / 'audits' / 'phase08_initialization_artifact_audit.json').read_text(encoding='utf-8'))
{
    'artifact_audit': artifact_audit,
    'training_executed': 'NO',
    'outer_test_predictions_generated': 'NO',
    'ready_for_contract_freeze_pre_persistence_audit': summary['ready_for_contract_freeze_pre_notebook'],
    'ready_for_modeling': 'NO',
}

{'artifact_audit': {'status': 'PASS',
  'required_directories': {'data': True,
   'configs': True,
   'manifests': True,
   'audits': True,
   'src': True,
   'scripts': True,
   'tests': True,
   'figures': True,
   'logs': True,
   'reports': True,
   'results/checkpoints': True,
   'results/predictions': True,
   'results/fold_metrics': True,
   'results/oof': True,
   'results/fusion': True,
   'results/shortcut': True,
   'results/statistics': True,
   'results/efficiency': True,
   'results/summaries': True},
  'required_artifacts': {'README.md': True,
   'task_plan.md': True,
   'notes.md': True,
   'configs/phase08_experiment_contract.json': True,
   'configs/phase08_environment.json': True,
   'configs/phase08_upstream_interface.json': True,
   'configs/phase08_dataset_conditions.json': True,
   'manifests/phase08_input_manifest.json': True,
   'manifests/phase08_fusion_feature_manifest.json': True,
   'manifests/phase08_performance_feature_manifest.json': True,
   'audits/pha

## Phase 08 Contract Freeze

This appended section freezes the execution contract, flight provenance sensitivity design, statistics, shortcut-evidence wording, and Phase 09 metadata handoff. It does not train models or create predictions.

### 8. Freeze contract artifacts after revalidating the initialization gate

In [9]:
from freeze_phase08_contract import freeze_contract
contract_summary = freeze_contract()
contract_summary

{'phase08_contract_freeze': 'PASS',
 'checksums': {'primary': True,
  'with_performance': True,
  'performance_only': True,
  'folds': True},
 'fusion_conditions_frozen': 5,
 'shortcut_conditions_frozen': 3,
 'flight_features_audited': 326,
 'flight_category_counts': {'BEHAVIORAL_RESPONSE': 323,
  'TASK_SETTING_OR_SCENARIO': 0,
  'AMBIGUOUS': 3},
 'flight_provenance_audit': 'PASS',
 'flight_conditions': {'FLIGHT_FULL': {'status': 'FROZEN_HDC_REFERENCE',
   'feature_count': 326,
   'feature_set_sha256': '8f44ff3924c5c5304069be5a2575cc223d9e1cc834aa27f301876ce6389b17d8',
   'ambiguous_features_retained': 3},
  'FLIGHT_BEHAVIORAL_ONLY': {'status': 'AUTHORIZED_UNIQUE_SENSITIVITY_CONDITION',
   'feature_count': 323,
   'feature_set_sha256': 'dea0483dec41903f3e1bdf30faf7918833c8f985ff134b0e81fa30ce86a8fdb9',
   'alias_of': None},
  'FLIGHT_TASK_SETTING_ONLY': {'status': 'NOT_FEASIBLE_EMPTY_PROVENANCE_GROUP',
   'feature_count': 0,
   'feature_set_sha256': '01ba4719c80b6fe911b091a7c05124b64ee

### 9. Data conditions, fusion matrix, and shortcut conditions

In [10]:
frozen_contract = json.loads((PHASE08_ROOT / 'configs' / 'phase08_frozen_contract.json').read_text(encoding='utf-8'))
{
    'evidence_roles': frozen_contract['evidence_roles'],
    'fusion_conditions': frozen_contract['fusion_conditions'],
    'shortcut_conditions': frozen_contract['shortcut_conditions'],
}

{'evidence_roles': {'PRIMARY_MAIN_EVIDENCE': {'dataset': 'primary_without_performance',
   'feature_count': 1176,
   'paper_role': 'ONLY_MAIN_RESULT'},
  'AUXILIARY_UPPER_BOUND_AND_SHORTCUT_ANALYSIS': {'dataset': 'auxiliary_with_performance',
   'feature_count': 1235},
  'AUXILIARY_PERFORMANCE_ONLY_SHORTCUT_ANALYSIS': {'dataset': 'performance_only',
   'feature_count': 59}},
 'fusion_conditions': {'FUSION_PE': {'groups': ['physiological_features',
    'eye_tracking_features'],
   'feature_count': 649,
   'execution': 'NEW_TRAINING_AUTHORIZED_AFTER_FREEZE'},
  'FUSION_PEH': {'groups': ['physiological_features',
    'eye_tracking_features',
    'head_movement_features'],
   'feature_count': 808,
   'execution': 'NEW_TRAINING_AUTHORIZED_AFTER_FREEZE'},
  'FUSION_PEHF': {'groups': ['physiological_features',
    'eye_tracking_features',
    'head_movement_features',
    'flight_parameter_features'],
   'feature_count': 1134,
   'execution': 'NEW_TRAINING_AUTHORIZED_AFTER_FREEZE'},
  'FULL_P

### 10. Flight provenance categories and sensitivity feasibility

In [11]:
flight_manifest = json.loads((PHASE08_ROOT / 'manifests' / 'phase08_flight_feature_provenance_manifest.json').read_text(encoding='utf-8'))
model_matrix = json.loads((PHASE08_ROOT / 'configs' / 'phase08_model_matrix.json').read_text(encoding='utf-8'))
{
    'flight_features_audited': flight_manifest['feature_count'],
    'category_counts': flight_manifest['category_counts'],
    'flight_sensitivity_conditions': model_matrix['flight_sensitivity_conditions'],
}

{'flight_features_audited': 326,
 'category_counts': {'BEHAVIORAL_RESPONSE': 323,
  'TASK_SETTING_OR_SCENARIO': 0,
  'AMBIGUOUS': 3},
 'flight_sensitivity_conditions': {'FLIGHT_FULL': {'status': 'FROZEN_HDC_REFERENCE',
   'feature_count': 326,
   'feature_set_sha256': '8f44ff3924c5c5304069be5a2575cc223d9e1cc834aa27f301876ce6389b17d8',
   'ambiguous_features_retained': 3},
  'FLIGHT_BEHAVIORAL_ONLY': {'status': 'AUTHORIZED_UNIQUE_SENSITIVITY_CONDITION',
   'feature_count': 323,
   'feature_set_sha256': 'dea0483dec41903f3e1bdf30faf7918833c8f985ff134b0e81fa30ce86a8fdb9',
   'alias_of': None},
  'FLIGHT_TASK_SETTING_ONLY': {'status': 'NOT_FEASIBLE_EMPTY_PROVENANCE_GROUP',
   'feature_count': 0,
   'feature_set_sha256': '01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b',
   'alias_of': None}}}

### 11. Frozen HDC/traditional interfaces and dynamic run count

In [12]:
{
    'interfaces': model_matrix['interfaces'],
    'run_counts': model_matrix['run_counts'],
    'duplicate_run_identifiers': json.loads((PHASE08_ROOT / 'configs' / 'phase08_execution_manifest.json').read_text(encoding='utf-8'))['duplicate_run_identifiers'],
}

{'interfaces': {'HDC_classification': 'PASS',
  'HDC_regression': 'PASS',
  'traditional_classification': 'PASS',
  'traditional_regression': 'PASS'},
 'run_counts': {'core_required_model_runs': 300,
  'traditional_flight_full_required_runs': 10,
  'unique_nonempty_nonaliased_flight_sensitivity_conditions': 1,
  'flight_sensitivity_model_runs': 60,
  'expected_total_model_runs': 370},
 'duplicate_run_identifiers': 0}

### 12. Comparison families, statistics, and shortcut-evidence wording

In [13]:
statistics = json.loads((PHASE08_ROOT / 'configs' / 'phase08_statistical_analysis_contract.json').read_text(encoding='utf-8'))
shortcut = json.loads((PHASE08_ROOT / 'configs' / 'phase08_shortcut_evidence_contract.json').read_text(encoding='utf-8'))
{
    'comparison_families': frozen_contract['comparison_families'],
    'oof_aggregation': frozen_contract['oof_aggregation'],
    'statistics': statistics,
    'shortcut_evidence_wording': shortcut,
}

{'comparison_families': {'status': 'FROZEN_SEPARATE_FAMILIES',
  'A_EARLY_FUSION': ['BEST_SINGLE_FLIGHT_REFERENCE',
   'FUSION_PE',
   'FUSION_PEH',
   'FUSION_PEHF',
   'FULL_PRIMARY_REFERENCE'],
  'B_PERFORMANCE_SHORTCUT': ['WITHOUT_PERFORMANCE_PRIMARY_REFERENCE',
   'WITH_PERFORMANCE_AUXILIARY',
   'PERFORMANCE_ONLY_AUXILIARY'],
  'C_FLIGHT_PROVENANCE_SENSITIVITY': ['FLIGHT_FULL',
   'FLIGHT_BEHAVIORAL_ONLY',
   'FLIGHT_TASK_SETTING_ONLY'],
  'single_cross_family_ranking': 'PROHIBITED'},
 'oof_aggregation': {'status': 'FROZEN',
  'HDC_classification': {'seeds': [42, 43, 44, 45, 46],
   'rule': 'mean five seed class scores then argmax',
   'tie_break': 'smaller class',
   'metrics': 'recompute from aggregated predictions',
   'best_seed_selection': 'PROHIBITED'},
  'HDC_regression': {'seeds': [42, 43, 44, 45, 46],
   'rule': 'mean five prediction_raw values then clip to [1.0, 4.0]',
   'metrics': 'recompute from aggregated predictions',
   'best_seed_selection': 'PROHIBITED'},
  'tra

### 13. Phase 09 metadata feasibility handoff

In [14]:
handoff = json.loads((PHASE08_ROOT / 'manifests' / 'phase08_to_phase09_generalization_handoff.json').read_text(encoding='utf-8'))
{
    'holdout_feasibility': {name: value['feasibility'] for name, value in handoff['holdouts'].items()},
    'guardrails': handoff['generalization_guardrails'],
}

{'holdout_feasibility': {'unseen_session': 'NOT_FEASIBLE_DUE_TO_METADATA',
  'unseen_scenario': 'NOT_FEASIBLE_DUE_TO_METADATA',
  'task_template': 'NOT_FEASIBLE_DUE_TO_METADATA',
  'route_or_configuration': 'NOT_FEASIBLE_DUE_TO_METADATA'},
 'guardrails': ['Subject-wise LOSO only evaluates subject generalization.',
  'LOSO does not automatically establish scenario generalization.',
  'Do not fabricate a scenario identifier that is absent from the metadata.']}

### 14. Run static tests without invoking modeling

In [15]:
import subprocess
test_process = subprocess.run(
    [sys.executable, '-m', 'unittest', 'discover', '-s', str(PHASE08_ROOT / 'tests'), '-p', 'test_phase08_contract.py', '-v'],
    cwd=PHASE08_ROOT, capture_output=True, text=True, check=False,
)
assert test_process.returncode == 0, test_process.stdout + test_process.stderr
{'returncode': test_process.returncode, 'result': 'PASS', 'details': (test_process.stdout + test_process.stderr)[-3000:]}

{'returncode': 0,
 'result': 'PASS',
 'details': 'test_data_and_fold_checksums (test_phase08_contract.Phase08ContractTests.test_data_and_fold_checksums) ... ok\ntest_dynamic_run_count_and_unique_identifiers (test_phase08_contract.Phase08ContractTests.test_dynamic_run_count_and_unique_identifiers) ... ok\ntest_flight_provenance_complete_and_exclusive (test_phase08_contract.Phase08ContractTests.test_flight_provenance_complete_and_exclusive) ... ok\ntest_fusion_and_performance_counts (test_phase08_contract.Phase08ContractTests.test_fusion_and_performance_counts) ... ok\ntest_hdc_frozen_parameters (test_phase08_contract.Phase08ContractTests.test_hdc_frozen_parameters) ... ok\ntest_no_training_or_upstream_modification (test_phase08_contract.Phase08ContractTests.test_no_training_or_upstream_modification) ... ok\ntest_oof_comparison_and_statistics_frozen (test_phase08_contract.Phase08ContractTests.test_oof_comparison_and_statistics_frozen) ... ok\ntest_provenance_sensitivity_subsets (test_pha

### 15. Confirm execution readiness and prohibited-operation state

In [16]:
freeze_audit = json.loads((PHASE08_ROOT / 'audits' / 'phase08_contract_freeze_audit.json').read_text(encoding='utf-8'))
{
    'contract_freeze': freeze_audit['status'],
    'training_executed': 'NO',
    'outer_test_predictions_generated': 'NO',
    'ready_for_execution_pending_notebook_persistence_audit': freeze_audit['status'] == 'PASS',
}

{'contract_freeze': 'PASS',
 'training_executed': 'NO',
 'outer_test_predictions_generated': 'NO',
 'ready_for_execution_pending_notebook_persistence_audit': True}

## Takeaways

Phase 08 is contract-frozen and not trained. The persisted contract authorizes a later, separate execution step only after this notebook's external persistence audit passes.

## Phase 08 Execution

This section records the audited 370-run frozen batch. It reads persisted artifacts only; it does not train, tune, consolidate OOF predictions, or invoke Phase 09.

In [1]:
from pathlib import Path
import json
PHASE08_ROOT = Path.cwd().resolve()
def load_audit(name):
    return json.loads((PHASE08_ROOT / 'audits' / name).read_text(encoding='utf-8'))
execution_summary = load_audit('phase08_execution_summary.json')
execution_summary

{'status': 'EXECUTION_COMPLETE_PENDING_OOF_CONSOLIDATION',
 'completed_runs': 370,
 'expected_runs': 370,
 'raw_prediction_rows': 31006,
 'expected_raw_prediction_rows': 31006,
 'model_task_counts': {'HDC_classification': 150,
  'TRADITIONAL_classification': 35,
  'HDC_regression': 150,
  'TRADITIONAL_regression': 35},
 'condition_counts': {'FUSION_PE': 60,
  'FUSION_PEH': 60,
  'FUSION_PEHF': 60,
  'WITH_PERFORMANCE_AUXILIARY': 60,
  'PERFORMANCE_ONLY_AUXILIARY': 60,
  'FLIGHT_BEHAVIORAL_ONLY': 60,
  'FLIGHT_FULL': 10},
 'flight_behavioral_runs': 60,
 'flight_full_new_runs': 10,
 'flight_task_setting_status': 'NOT_FEASIBLE_EMPTY_PROVENANCE_GROUP',
 'failed_run_events': 0,
 'recovered_valid_checkpoints': 0,
 'executor_validation': 'PASS',
 'checkpoint_integrity': 'PASS',
 'coverage_audit': 'PASS',
 'leakage_audit': 'PASS',
 'artifact_audit': 'PASS',
 'notebook_persistence': 'PASS',
 'outer_test_used_for_tuning': False,
 'final_oof_consolidation_executed': False,
 'phase09_executed': Fa

### 16. Executor gate and completed-run coverage

In [2]:
executor = load_audit('phase08_executor_validation_audit.json')
coverage = load_audit('phase08_execution_coverage_audit.json')
{
    'executor_validation': execution_summary['executor_validation'],
    'completed_runs': f"{execution_summary['completed_runs']}/{execution_summary['expected_runs']}",
    'raw_prediction_rows': f"{execution_summary['raw_prediction_rows']}/{execution_summary['expected_raw_prediction_rows']}",
    'model_task_counts': execution_summary['model_task_counts'],
    'condition_counts': execution_summary['condition_counts'],
    'failed_run_events': execution_summary['failed_run_events'],
    'recovered_valid_checkpoints': execution_summary['recovered_valid_checkpoints'],
}

{'executor_validation': 'PASS',
 'completed_runs': '370/370',
 'raw_prediction_rows': '31006/31006',
 'model_task_counts': {'HDC_classification': 150,
  'TRADITIONAL_classification': 35,
  'HDC_regression': 150,
  'TRADITIONAL_regression': 35},
 'condition_counts': {'FUSION_PE': 60,
  'FUSION_PEH': 60,
  'FUSION_PEHF': 60,
  'WITH_PERFORMANCE_AUXILIARY': 60,
  'PERFORMANCE_ONLY_AUXILIARY': 60,
  'FLIGHT_BEHAVIORAL_ONLY': 60,
  'FLIGHT_FULL': 10},
 'failed_run_events': 0,
 'recovered_valid_checkpoints': 0}

### 17. Checkpoint integrity, leakage, and artifact audits

In [3]:
checkpoint = load_audit('phase08_checkpoint_integrity_audit.json')
leakage = load_audit('phase08_execution_leakage_audit.json')
artifacts = load_audit('phase08_execution_artifact_audit.json')
{
    'checkpoint_integrity': execution_summary['checkpoint_integrity'],
    'execution_coverage': execution_summary['coverage_audit'],
    'execution_leakage': execution_summary['leakage_audit'],
    'artifact_audit': execution_summary['artifact_audit'],
    'outer_test_used_for_tuning': execution_summary['outer_test_used_for_tuning'],
    'final_oof_consolidation_executed': execution_summary['final_oof_consolidation_executed'],
    'phase09_executed': execution_summary['phase09_executed'],
}

{'checkpoint_integrity': 'PASS',
 'execution_coverage': 'PASS',
 'execution_leakage': 'PASS',
 'artifact_audit': 'PASS',
 'outer_test_used_for_tuning': False,
 'final_oof_consolidation_executed': False,
 'phase09_executed': False}

### 18. Execution boundary and handoff

In [4]:
{
    'status': execution_summary['status'],
    'flight_task_setting_status': execution_summary['flight_task_setting_status'],
    'next_permitted_step': 'PHASE_08_OOF_CONSOLIDATION',
    'oof_consolidation_performed_here': False,
}

{'status': 'EXECUTION_COMPLETE_PENDING_OOF_CONSOLIDATION',
 'flight_task_setting_status': 'NOT_FEASIBLE_EMPTY_PROVENANCE_GROUP',
 'next_permitted_step': 'PHASE_08_OOF_CONSOLIDATION',
 'oof_consolidation_performed_here': False}

## Execution Takeaways

All 370 frozen model-runs completed and passed independent coverage, checkpoint, leakage, and artifact audits. The execution produced 31,006 raw outer-test prediction rows. Canonical OOF consolidation and Phase 09 remain unexecuted.

## Phase 08 Canonical OOF and Final Analysis

Executed, read-only presentation of persisted OOF, metric, statistical, figure, limitation, and handoff artifacts. No model training, tuning, freeze, or Phase 09 execution occurs here.

In [1]:
from pathlib import Path
import json, pandas as pd
PHASE08_ROOT=Path.cwd().resolve()
def audit(n): return json.loads((PHASE08_ROOT/'audits'/n).read_text(encoding='utf-8'))
oof_index=pd.read_csv(PHASE08_ROOT/'results/oof/phase08_canonical_oof_index.csv')
{'canonical_rows':int(oof_index.rows.sum()),'legal_combinations':len(oof_index),'coverage':audit('phase08_oof_coverage_audit.json')['status'],'alignment':audit('phase08_oof_alignment_audit.json')['status'],'leakage':audit('phase08_oof_leakage_audit.json')['status']}

{'canonical_rows': 10894,
 'legal_combinations': 26,
 'coverage': 'PASS',
 'alignment': 'PASS',
 'leakage': 'PASS'}

### Independent metric recalculation and fusion comparison

In [2]:
classification=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_classification_metrics.csv')
regression=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_regression_metrics.csv')
fusion=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_fusion_increment_analysis.csv')
{'metric_audit':audit('phase08_metric_recalculation_audit.json')['status'],'classification':classification[['condition','model_family','source_status','macro_f1']].to_dict('records'),'regression':regression[['condition','model_family','source_status','bounded_mae']].to_dict('records'),'registered_fusion_comparisons':len(fusion)}

{'metric_audit': 'PASS',
 'classification': [{'condition': 'BEST_SINGLE_FLIGHT_REFERENCE',
   'model_family': 'HDC',
   'source_status': 'REUSED_FROZEN_REFERENCE',
   'macro_f1': 0.8634578130317547},
  {'condition': 'FLIGHT_BEHAVIORAL_ONLY',
   'model_family': 'HDC',
   'source_status': 'NEW_PHASE08_RUN',
   'macro_f1': 0.8543509417188794},
  {'condition': 'FLIGHT_BEHAVIORAL_ONLY',
   'model_family': 'TRADITIONAL',
   'source_status': 'NEW_PHASE08_RUN',
   'macro_f1': 0.9450797501684948},
  {'condition': 'FLIGHT_FULL',
   'model_family': 'HDC',
   'source_status': 'REUSED_FROZEN_REFERENCE',
   'macro_f1': 0.8634578130317547},
  {'condition': 'FLIGHT_FULL',
   'model_family': 'TRADITIONAL',
   'source_status': 'NEW_PHASE08_RUN',
   'macro_f1': 0.952313065384175},
  {'condition': 'FULL_PRIMARY_REFERENCE',
   'model_family': 'HDC',
   'source_status': 'REUSED_FROZEN_REFERENCE',
   'macro_f1': 0.8710573880254382},
  {'condition': 'FULL_PRIMARY_REFERENCE',
   'model_family': 'TRADITIONAL',


### Flight behavioral sensitivity and shortcut evidence

In [3]:
flight=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_flight_behavioral_sensitivity.csv')
shortcut=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_shortcut_evidence_matrix.csv')
limits=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_generalization_evidence_limits.csv')
{'flight_features':{'full':326,'behavioral_only':323,'ambiguous':3,'task_setting':0},'flight_comparisons':flight.to_dict('records'),'shortcut_comparisons':shortcut.to_dict('records'),'limitations':limits.to_dict('records')}

{'flight_features': {'full': 326,
  'behavioral_only': 323,
  'ambiguous': 3,
  'task_setting': 0},
 'flight_comparisons': [{'comparison_family': 'C_FLIGHT_PROVENANCE_SENSITIVITY',
   'model_family': 'HDC',
   'task': 'classification',
   'metric': 'macro_f1',
   'metric_direction': 'higher_is_better',
   'left_condition': 'FLIGHT_FULL',
   'right_condition': 'FLIGHT_BEHAVIORAL_ONLY',
   'n_subjects': 35,
   'left_mean': 0.8529251700680271,
   'right_mean': 0.8415450026164312,
   'right_minus_left': -0.011380167451596,
   'wilcoxon_statistic': 13.0,
   'p_value': 0.136838309563315,
   'rank_biserial_right_minus_left': -0.5272727272727272,
   'bootstrap_ci_low': -0.0290919021454735,
   'bootstrap_ci_high': 0.0046249345892202,
   'p_holm': 0.136838309563315,
   'significant_holm_0_05': False},
  {'comparison_family': 'C_FLIGHT_PROVENANCE_SENSITIVITY',
   'model_family': 'TRADITIONAL',
   'task': 'classification',
   'metric': 'macro_f1',
   'metric_direction': 'higher_is_better',
   'lef

### Subject-level statistics, figures, and handoff

In [4]:
pairwise=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_pairwise_statistics.csv')
bootstrap=pd.read_csv(PHASE08_ROOT/'results/summaries/phase08_bootstrap_confidence_intervals.csv')
figures=sorted(p.name for p in (PHASE08_ROOT/'figures').glob('phase08_*.*'))
handoff=json.loads((PHASE08_ROOT/'configs/phase09_generalization_handoff.json').read_text(encoding='utf-8'))
{'statistical_unit':'subject_id','n_subjects':35,'wilcoxon_rows':len(pairwise),'holm_complete':bool(pairwise.p_holm.notna().all()),'bootstrap_rows':len(bootstrap),'figures':figures,'phase09_handoff_status':handoff['status'],'phase09_executed':handoff['phase09_executed']}

{'statistical_unit': 'subject_id',
 'n_subjects': 35,
 'wilcoxon_rows': 26,
 'holm_complete': True,
 'bootstrap_rows': 64,
 'figures': ['phase08_classification_condition_comparison.pdf',
  'phase08_classification_condition_comparison.png',
  'phase08_fusion_increment_effects.pdf',
  'phase08_fusion_increment_effects.png',
  'phase08_regression_condition_comparison.pdf',
  'phase08_regression_condition_comparison.png',
  'phase08_shortcut_sensitivity.pdf',
  'phase08_shortcut_sensitivity.png',
  'phase08_subject_level_effects.pdf',
  'phase08_subject_level_effects.png'],
 'phase09_handoff_status': 'NOT_FEASIBLE_DUE_TO_METADATA',
 'phase09_executed': False}

## Final Analysis Takeaways

Phase 08 contains 10,894 canonical OOF rows with independently recomputed metrics and paired subject-level inference. Performance features remain auxiliary shortcut-risk evidence; missing unseen-condition metadata limits generalization claims. Analysis is complete pending a separate freeze step. Phase 09 was not executed.

## Phase 08 Final Freeze Summary

This isolated, executed summary records the final Phase 08 freeze. Historical cells and outputs above are preserved. No model training, prediction generation, or Phase 09 execution occurs here.

In [1]:
from pathlib import Path
import json
phase08_root = Path.cwd().resolve()
freeze = json.loads((phase08_root/'configs/phase08_freeze.json').read_text(encoding='utf-8'))
manifest = json.loads((phase08_root/'manifests/phase08_final_manifest.json').read_text(encoding='utf-8'))
{'runs':'370/370','raw_prediction_rows':31006,'canonical_oof_rows':10894,'final_audits':'PASS','manifest_saved':True,'freeze_file_saved':True,'phase08_status':freeze['status'],'phase09_executed':freeze['phase09_executed'],'ready_for_phase09':freeze['ready_to_proceed_to_phase09']}

{'runs': '370/370',
 'raw_prediction_rows': 31006,
 'canonical_oof_rows': 10894,
 'final_audits': 'PASS',
 'manifest_saved': True,
 'freeze_file_saved': True,
 'phase08_status': 'FROZEN',
 'phase09_executed': False,
 'ready_for_phase09': True}